import type { Metadata } from "next"

import {
  LINKS,
  MarketingFooter,
  MarketingNav,
  auditors,
  backers,
  externalLinkProps,
} from "@/components/marketing/marketing-chrome"

export const metadata: Metadata = {
  title: "Overlay Listing Application",
  description:
    "Apply to launch a long-tail perpetual market on Overlay with protocol-managed liquidity and project revenue share.",
}

const advantageCards = [
  {
    icon: "payments",
    title: "Trading fee rev-share",
    description:
      "Earn a percentage of trading fees generated by your market after launch.",
  },
  {
    icon: "shield",
    title: "Hedging for holders",
    description:
      "Give your community a liquid way to manage exposure without selling spot.",
  },
  {
    icon: "account_balance",
    title: "Stablecoin settlement",
    description:
      "Trader PnL settles in stablecoins, so users avoid unwanted OVL price exposure.",
  },
  {
    icon: "campaign",
    title: "Community visibility",
    description:
      "A live perps market gives your asset a new venue and launch signal.",
  },
]

const protocolSteps = [
  "Trader opens position",
  "Protocol tracks PnL",
  "OVL supply auto mint/burns",
]

const comparisonRows = [
  {
    metric: "Market maker",
    cex: "Required + retainer",
    overlay: "Not needed",
  },
  {
    metric: "Revenue share",
    cex: "No",
    overlay: "Yes",
  },
  {
    metric: "Delisting risk",
    cex: "High",
    overlay: "Low",
  },
]

const liquidityColumns = [
  {
    title: "Other perps",
    tone: "muted",
    items: [
      "Need millions in liquidity requirements to list.",
      "Capital gets locked across multiple venues.",
      "Most long-tail projects never qualify.",
    ],
  },
  {
    title: "CEX listings",
    tone: "muted",
    items: [
      "5-6 figure integration fees.",
      "Legal, market-maker, and listing committee requirements.",
      "Delisting risk when market volume fades.",
    ],
  },
  {
    title: "Overlay",
    tone: "primary",
    items: [
      "One-time integration path.",
      "Zero external liquidity requirement.",
      "Passive revenue share from day one.",
    ],
  },
]

const liveMarkets = [
  {
    detail: "Live on Overlay",
    ticker: "$DASH",
    tweetHref: "https://x.com/dashpay/status/2031750873676705884",
  },
  {
    detail: "Live on Overlay",
    ticker: "$CHZ",
    tweetHref: "https://x.com/Chiliz/status/2045049440939991359",
  },
  {
    detail: "Live on Overlay",
    ticker: "$MOCA",
    tweetHref: "https://x.com/OverlayProtocol/status/2036835562448117918",
  },
  {
    detail: "On-chain live",
    ticker: "$PLUME",
    tweetHref: "https://x.com/OverlayProtocol/status/2037197958035427520",
  },
  {
    detail: "On-chain live",
    ticker: "$AERO",
    tweetHref: "https://x.com/OverlayProtocol/status/2032157908105076957",
  },
  {
    detail: "On-chain live",
    ticker: "$VVV",
    tweetHref: "https://x.com/OverlayProtocol/status/2040127223718633568",
  },
]

const journeySteps = [
  {
    title: "Apply & list",
    description:
      "Submit token details and data-feed context for an integration review.",
  },
  {
    title: "Market goes live",
    description:
      "Traders can go long or short as soon as the market is deployed.",
  },
  {
    title: "Protocol handles risk",
    description:
      "Overlay manages settlement through its mint/burn risk mechanism.",
  },
  {
    title: "You earn rev-share",
    description:
      "Collect ongoing protocol revenue from trade flow generated by your market.",
  },
]

const faqItems = [
  {
    question: "Are there any integration fees?",
    answer:
      "Yes. There is a standard one-time integration fee to cover technical setup and data-feed review. Overlay does not require ongoing market-maker retainers.",
  },
  {
    question: "How long does the listing process take?",
    answer:
      "The listing process typically takes 1-3 weeks. Timely communication and feed verification can shorten that window.",
  },
  {
    question: "Which data feeds are supported?",
    answer:
      "Overlay can support verifiable and manipulation-resistant feeds, including established oracle feeds and custom feeds that can be reviewed.",
  },
  {
    question: "How do I make sure there is sufficient liquidity?",
    answer:
      "Liquidity is handled by the protocol. Traders trade against Overlay's risk engine rather than a dedicated project-funded market maker.",
  },
]

const LISTING_FORM_URL =
  "https://docs.google.com/forms/d/e/1FAIpQLSdQr6GX8a5khZpxcB7Z6JDEvx1FsPoKQhF78D1qaVV6BslUig/viewform"

function SectionHeading({
  eyebrow,
  title,
  description,
}: {
  eyebrow?: string
  title: string
  description?: string
}) {
  return (
    <div className="space-y-4">
      {eyebrow ? (
        <span className="font-label-caps text-xs text-primary tracking-[0.2em] uppercase">
          {eyebrow}
        </span>
      ) : null}
      <h2 className="font-headline-xl text-4xl md:text-5xl text-secondary text-balance">
        {title}
      </h2>
      {description ? (
        <p className="font-body-md text-lg text-on-surface-variant max-w-2xl leading-relaxed">
          {description}
        </p>
      ) : null}
    </div>
  )
}

function ListingTerminalPanel() {
  return (
    <div className="bg-surface-container-low border border-outline-variant/50 rounded-xl p-1 shadow-2xl relative scanline-effect backdrop-blur-md">
      <div className="bg-surface-container-highest rounded-t-lg flex items-center justify-between gap-4 p-3 border-b border-outline-variant/50">
        <div className="flex gap-2.5">
          <span className="h-3 w-3 rounded-full bg-primary-container" />
          <span className="h-3 w-3 rounded-full bg-secondary-container" />
          <span className="h-3 w-3 rounded-full bg-outline-variant" />
        </div>
        <span className="font-data-md text-[10px] sm:text-xs text-on-surface-variant tracking-widest whitespace-nowrap">
          OVL // LISTING_PIPELINE
        </span>
      </div>
      <div className="rounded-b-lg bg-surface-container-lowest p-5 sm:p-6 space-y-5">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {[
            ["TARGET", "LONG-TAIL PERP"],
            ["LIQUIDITY REQUIRED", "$0"],
            ["SETTLEMENT", "STABLECOIN"],
            ["REVENUE", "FEE SHARE"],
          ].map(([label, value]) => (
            <div
              className="border border-outline-variant/50 bg-background/70 p-4"
              key={label}
            >
              <span className="font-label-caps text-[10px] text-on-surface-variant uppercase tracking-widest">
                {label}
              </span>
              <span className="mt-4 block font-data-lg text-xl text-primary">
                {value}
              </span>
            </div>
          ))}
        </div>
        <div className="border border-primary/20 bg-primary/5 p-5">
          <span className="font-label-caps text-[10px] text-primary uppercase tracking-widest">
            Feed review
          </span>
          <div className="mt-4 space-y-3 font-data-md text-sm">
            {[
              "Manipulation resistance",
              "Update frequency",
              "Asset coverage",
              "Launch support",
            ].map((item) => (
              <div className="flex items-center justify-between gap-4" key={item}>
                <span className="text-on-surface-variant">{item}</span>
                <span className="text-secondary-container">READY</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

export default function ListingPage() {
  return (
    <>
      <MarketingNav activePage="listing" />
      <main className="pt-24 md:pt-32 pb-16 md:pb-24">
        <section className="max-w-container-max mx-auto px-6 pt-16 pb-14 md:pt-24 md:pb-20 relative overflow-hidden">
          <div className="absolute inset-0 bg-grid-overlay opacity-30 pointer-events-none z-0" />
          <div className="relative z-10 grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16 items-center">
            <div className="lg:col-span-7 space-y-7 md:space-y-8">
              <span className="inline-flex w-fit items-center gap-2 border border-primary/30 bg-primary/10 px-3 py-1 font-label-caps text-[10px] text-primary uppercase tracking-widest">
                <span className="h-2 w-2 rounded-full bg-primary-container animate-pulse" />
                Live perps. Days to list.
              </span>
              <div className="space-y-5 md:space-y-6">
                <h1 className="font-headline-xl text-5xl md:text-6xl text-secondary max-w-3xl leading-tight text-balance">
                  Your token deserves a perps market.
                </h1>
                <p className="font-body-md text-lg md:text-xl text-on-surface-variant max-w-2xl leading-relaxed">
                  Stop waiting for CEX approval or liquidity requirements that
                  keep your project small. Overlay enables perpetual markets for
                  assets with verifiable data feeds.
                </p>
              </div>
              <div className="flex flex-wrap gap-4 pt-2">
                <a
                  className="inline-flex items-center justify-center bg-primary text-on-primary font-label-caps text-label-caps px-6 py-3.5 rounded uppercase tracking-wider hover:bg-primary-container transition-colors duration-200"
                  href="#apply-form"
                >
                  Apply to List
                </a>
                <a
                  className="inline-flex items-center justify-center gap-2 bg-transparent border border-primary/40 text-primary font-label-caps text-label-caps px-6 py-3.5 rounded uppercase tracking-wider hover:bg-primary/10 transition-all duration-200 shadow-[0_0_15px_rgba(0,240,255,0.1)] hover:shadow-[0_0_20px_rgba(0,240,255,0.2)]"
                  href={LINKS.whitepaperV1}
                  {...externalLinkProps}
                >
                  <span>Read Whitepaper</span>
                  <span className="material-symbols-outlined text-[18px]">
                    description
                  </span>
                </a>
              </div>
            </div>
            <div className="lg:col-span-5">
              <ListingTerminalPanel />
            </div>
          </div>
        </section>

        <section className="max-w-container-max mx-auto px-6 py-10 md:py-14">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-12 border-y border-outline-variant/30 py-10">
            <div>
              <span className="font-label-caps text-xs text-on-surface-variant tracking-[0.3em] uppercase block mb-6">
                Backed By
              </span>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                {backers.map((backer) => (
                  <div
                    className="min-h-16 border border-outline-variant/40 bg-surface-container-lowest px-4 flex items-center justify-center grayscale contrast-125"
                    key={backer}
                  >
                    <span className="font-headline-md text-base text-secondary font-bold tracking-tighter text-center uppercase">
                      {backer}
                    </span>
                  </div>
                ))}
              </div>
            </div>
            <div>
              <span className="font-label-caps text-xs text-on-surface-variant tracking-[0.3em] uppercase block mb-6">
                Audited By
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {auditors.slice(0, 4).map((auditor) => (
                  <a
                    aria-label={auditor.externalLinkText}
                    className="min-h-16 border border-outline-variant/40 bg-surface-container-lowest px-4 flex items-center justify-center gap-3 grayscale contrast-125 hover:grayscale-0 transition-all"
                    href={auditor.completedAuditHref}
                    key={auditor.name}
                    rel="noopener noreferrer"
                    target="_blank"
                  >
                    <span className="material-symbols-outlined text-primary text-lg">
                      verified_user
                    </span>
                    <span className="font-headline-md text-base text-secondary font-bold tracking-tighter text-center uppercase leading-tight">
                      {auditor.name}
                    </span>
                  </a>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section className="max-w-container-max mx-auto px-6 py-16 md:py-24">
          <div className="text-center mb-12 md:mb-16">
            <SectionHeading
              description="For projects that want market access without liquidity lockups and market-maker retainers."
              title="The unfair advantage."
            />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5 lg:gap-6">
            {advantageCards.map((card, index) => (
              <div
                className={[
                  "bg-surface-container-low border border-outline-variant/50 p-6 md:p-8 shadow-xl transition-colors duration-200 hover:border-primary/40",
                  index === 0 ? "border-l-4 border-l-primary" : "",
                ].join(" ")}
                key={card.title}
              >
                <span className="material-symbols-outlined text-2xl text-primary mb-6 block">
                  {card.icon}
                </span>
                <h3 className="font-headline-md text-2xl text-secondary mb-3">
                  {card.title}
                </h3>
                <p className="font-body-md text-base text-on-surface-variant leading-relaxed">
                  {card.description}
                </p>
              </div>
            ))}
          </div>
          <div className="mt-10 border border-primary/20 bg-primary/5 px-5 py-4 text-center font-data-md text-sm text-primary uppercase tracking-widest">
            One-time integration path. Then earn passively.
          </div>
        </section>

        <section className="max-w-container-max mx-auto px-6 py-16 md:py-24">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-start">
            <div className="space-y-8">
              <SectionHeading
                eyebrow="The Technology"
                title="The protocol is the market maker."
                description="Overlay uses a mint/burn mechanism that manages PnL balances across the network. No fragmented liquidity pools. No predatory market makers."
              />
              <div className="space-y-4">
                {protocolSteps.map((step, index) => (
                  <div className="flex items-center gap-4" key={step}>
                    <div
                      className={[
                        "h-11 w-11 shrink-0 border flex items-center justify-center font-data-md text-sm",
                        index === protocolSteps.length - 1
                          ? "border-primary bg-primary text-on-primary"
                          : "border-primary/40 bg-primary/10 text-primary",
                      ].join(" ")}
                    >
                      {String(index + 1).padStart(2, "0")}
                    </div>
                    <div className="min-h-14 flex flex-1 items-center border border-outline-variant/50 bg-surface-container-low px-4">
                      <span className="font-data-md text-sm uppercase tracking-wider text-on-surface">
                        {step}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className="border border-outline-variant/50 bg-surface-container-low p-1 shadow-2xl">
              <table className="w-full text-left font-data-md text-sm">
                <thead className="bg-surface-container-high text-on-surface-variant uppercase text-[10px] tracking-widest">
                  <tr>
                    <th className="p-4">Metric</th>
                    <th className="p-4">CEX</th>
                    <th className="p-4 text-primary">Overlay</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-outline-variant/50">
                  {comparisonRows.map((row) => (
                    <tr key={row.metric}>
                      <td className="p-4 text-on-surface-variant">
                        {row.metric}
                      </td>
                      <td className="p-4 text-on-surface">{row.cex}</td>
                      <td className="p-4 text-primary font-semibold">
                        {row.overlay}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </section>

        <section className="bg-surface-container-lowest border-y border-outline-variant/30">
          <div className="max-w-container-max mx-auto px-6 py-16 md:py-24">
            <div className="mb-12 md:mb-16">
              <SectionHeading
                eyebrow="The Solution"
                title="The Liquidity Gap"
                description="Traditional markets ignore the long tail. Overlay bridges the gap."
              />
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5 lg:gap-6">
              {liquidityColumns.map((column) => (
                <div
                  className={[
                    "border p-6 md:p-8 bg-surface-container-low",
                    column.tone === "primary"
                      ? "border-primary/40 bg-primary/5"
                      : "border-outline-variant/50",
                  ].join(" ")}
                  key={column.title}
                >
                  <h3
                    className={[
                      "font-headline-md text-2xl mb-6",
                      column.tone === "primary"
                        ? "text-primary"
                        : "text-secondary",
                    ].join(" ")}
                  >
                    {column.title}
                  </h3>
                  <ul className="space-y-4">
                    {column.items.map((item) => (
                      <li className="flex items-start gap-3" key={item}>
                        <span
                          className={[
                            "material-symbols-outlined text-xl",
                            column.tone === "primary"
                              ? "text-secondary-container"
                              : "text-outline",
                          ].join(" ")}
                        >
                          {column.tone === "primary" ? "check_circle" : "close"}
                        </span>
                        <span className="font-body-md text-base text-on-surface-variant leading-relaxed">
                          {item}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="max-w-container-max mx-auto px-6 py-16 md:py-24">
          <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-8 mb-10 md:mb-12">
            <SectionHeading
              description="Join projects already using Overlay perps infrastructure for long-tail market exposure."
              title="Projects have already chosen Overlay"
            />
            <a
              className="inline-flex w-fit items-center gap-3 text-primary font-label-caps text-[11px] uppercase tracking-widest hover:gap-5 transition-all duration-300"
              href={LINKS.markets}
              {...externalLinkProps}
            >
              View Markets
              <span className="material-symbols-outlined text-sm">
                arrow_forward
              </span>
            </a>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 lg:gap-6">
            {liveMarkets.map((market) => (
              <div
                className="group bg-surface-container-low border border-outline-variant/50 p-6 md:p-8 relative overflow-hidden transition-colors hover:border-primary/40"
                key={market.ticker}
              >
                <div className="flex justify-between items-start gap-4 mb-10">
                  <div className="space-y-3">
                    <span className="inline-flex items-center gap-2 bg-secondary-container/10 px-2 py-1 font-label-caps text-[10px] text-secondary-container uppercase tracking-widest">
                      <span className="h-1.5 w-1.5 rounded-full bg-secondary-container" />
                      Verified Market
                    </span>
                    <h3 className="font-data-lg text-4xl text-secondary group-hover:text-primary transition-colors">
                      {market.ticker}
                    </h3>
                  </div>
                  <span className="material-symbols-outlined text-primary text-xl">
                    candlestick_chart
                  </span>
                </div>
                <div className="flex justify-between items-center gap-4 border-t border-outline-variant/40 pt-4">
                  <span className="font-label-caps text-[10px] text-on-surface-variant uppercase tracking-widest">
                    {market.detail}
                  </span>
                  <a
                    className="inline-flex items-center gap-1 font-data-md text-xs text-primary uppercase hover:text-primary-container transition-colors"
                    href={market.tweetHref}
                    {...externalLinkProps}
                  >
                    View Tweet
                    <span className="material-symbols-outlined text-xs">
                      arrow_outward
                    </span>
                  </a>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="bg-surface-container-lowest border-y border-outline-variant/30">
          <div className="max-w-container-max mx-auto px-6 py-16 md:py-24">
            <div className="mb-14 md:mb-20">
              <SectionHeading
                title="Listing Journey"
                description="Bring your project to market without operational complexity."
              />
            </div>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-8 md:gap-0 relative">
              <div className="hidden md:block absolute top-6 left-0 w-full h-px bg-outline-variant/50" />
              {journeySteps.map((step, index) => (
                <div
                  className="relative flex flex-col items-start gap-4 md:px-4"
                  key={step.title}
                >
                  <div
                    className={[
                      "h-12 w-12 border bg-background flex items-center justify-center font-data-md text-sm z-10",
                      index === 0
                        ? "border-primary text-primary"
                        : "border-outline-variant text-on-surface-variant",
                    ].join(" ")}
                  >
                    {String(index + 1).padStart(2, "0")}
                  </div>
                  <h3 className="font-headline-md text-2xl text-secondary">
                    {step.title}
                  </h3>
                  <p className="font-body-md text-base text-on-surface-variant leading-relaxed">
                    {step.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="max-w-4xl mx-auto px-6 py-16 md:py-24">
          <h2 className="font-headline-xl text-4xl md:text-5xl text-secondary text-center mb-10 md:mb-12">
            Frequently Asked Questions
          </h2>
          <div className="space-y-4">
            {faqItems.map((item) => (
              <details
                className="group bg-surface-container-low border border-outline-variant/50 p-5 md:p-6"
                key={item.question}
              >
                <summary className="flex justify-between items-center gap-6 cursor-pointer list-none font-headline-md text-xl text-secondary">
                  <span>{item.question}</span>
                  <span className="material-symbols-outlined text-primary transition-transform group-open:rotate-180">
                    expand_more
                  </span>
                </summary>
                <p className="mt-4 font-body-md text-base text-on-surface-variant leading-relaxed">
                  {item.answer}
                </p>
              </details>
            ))}
          </div>
        </section>

        <section
          className="bg-surface-container border-y border-outline-variant/30"
          id="apply-form"
        >
          <div className="max-w-container-max mx-auto px-6 py-16 md:py-24">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-12 items-start">
              <div className="space-y-8">
                <SectionHeading
                  title="Apply for Listing"
                  description="Overlay reviews project technology, tokenomics, and feed viability to determine the right path to a high-quality perps market."
                />
                <div className="space-y-6">
                  {[
                    {
                      href: "mailto:listings@overlay.market",
                      icon: "mail",
                      text: "listings@overlay.market",
                      title: "Direct contact",
                    },
                    {
                      icon: "groups",
                      text: "Each project gets guidance through review and launch.",
                      title: "Dedicated support",
                    },
                  ].map(({ href, icon, text, title }) => (
                    <div className="flex gap-4" key={title}>
                      <span className="material-symbols-outlined text-primary">
                        {icon}
                      </span>
                      <div>
                        <p className="font-headline-md text-lg text-secondary">
                          {title}
                        </p>
                        {href ? (
                          <a
                            className="font-body-md text-base text-on-surface-variant underline-offset-4 hover:text-primary hover:underline"
                            href={href}
                          >
                            {text}
                          </a>
                        ) : (
                          <p className="font-body-md text-base text-on-surface-variant">
                            {text}
                          </p>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              <div className="bg-surface-container-low border border-outline-variant/50 rounded-xl shadow-2xl p-8 md:p-12 flex flex-col items-center gap-6 text-center">
                <span className="material-symbols-outlined text-4xl text-primary">
                  rocket_launch
                </span>
                <div className="space-y-3">
                  <h3 className="font-headline-md text-2xl text-secondary">
                    Ready to list?
                  </h3>
                  <p className="font-body-md text-base text-on-surface-variant leading-relaxed max-w-sm">
                    Fill out the listing application with your token and
                    data-feed details. Our team reviews every submission and
                    follows up within 1-3 weeks.
                  </p>
                </div>
                <a
                  className="inline-flex w-full sm:w-auto items-center justify-center gap-2 bg-primary text-on-primary font-label-caps text-label-caps px-8 py-4 rounded uppercase tracking-widest hover:bg-primary-container active:scale-[0.98] transition-all"
                  href={LISTING_FORM_URL}
                  {...externalLinkProps}
                >
                  List Your Perps Market
                  <span className="material-symbols-outlined text-[18px]">
                    arrow_outward
                  </span>
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
      <MarketingFooter />
    </>
  )
}
